; scrolltxt

                ;    12345678901234567890!2345678901234567890
; scrolltxt

	.byte	2,4,"                     ",1,8,"       CHIP O       "
	.byte   2,8,"                  ",1,8,"     DJANGO ONE     "

	.byte	2,4,"                ",2,2,"  FINAL VERSION FROM RABENAUGE"
	.byte    " AND THE GREAT COMPOSERS OF THE AMIGA SCENE.       DONE FOR THE DEADLINE PARTY 2021.         "
	.byte	"            ACORN ARCHIMEDES PORT BY BITSHIFTERS!  LOOK ALSO FOR THE AMIGA & ATARI VERSIONS OF THIS CHIPTUNE PACK!       "
	.byte	2,4,"                                       "
	.byte    "               AND NOW THE CREDITS FOR THIS PACK:                "
	.byte	2,2,"  AMIGA-CODE: BODO & INSANE      AMIGA-SPRITE-LOADER: KRILL      ATARI-CODE: INSANE     ATARI-PAULA-EMULATOR: LEONARD/OXYGENE    "
	.byte    "  ARCHIE-CODE: KIERAN/BITSHIFTERS     ARCHIE-MUSIC-PLAYER & RASTERMAN: PHOENIX/QUANTUM      "
	.byte    "HEAVY TECHNICAL SUPPORT: BIFAT & OKEANOS      GFX: TITUS & BODO     "
	.byte    "MUSIC ORGANIZER: VIRGILL                        AND THE MUSIC FROM THE COMPOSERS: CURT COOL,DALEZY,JUICE,MA2E,OKEANOS,SLASH,TRIACE,VIRGILL     "
	.byte    "                WE HOPE YOU LIKE THIS PACK!     COLLECT THEM ALL!! :)               "
	.byte	1,8,2,8,"     GREETINGS:     "
        .byte	"ABYSS    "
        .byte	"ABYSS CONNECTION    "
        .byte	"ALTAIR    "
        .byte	"ATLANTIS    "
        .byte	"ATTENTION WHORE    "
        .byte	"BAUKNECHT    "
        .byte	"CHECKPOINT    "
        .byte	"CYANOACRYLATE DREAMS    "
        .byte	"DANISH GOLD    "
        .byte	"DELYSID    "
        .byte	"DESIRE    "
        .byte	"DEAD HACKERS SOCIETY    "
        .byte	"DIGITAL DEMOLITION KREW    "
        .byte	"EXCESS    "
        .byte	"FINNISH GOLD    "
        .byte	"GENESIS PROJECTS    "
        .byte	"GNUMPF POSSE    "
        .byte	"HAUJOBB    "
        .byte	"INSANE    "
        .byte	"JAC    "
        .byte	"K2    "
        .byte	"MANIACS OF NOISE    "
        .byte	"MAYDAY    "
        .byte	"MELON    "
        .byte	"MOODS PLATEAU    "
        .byte	"MTP    "
        .byte	"MYSTIC BYTES    "
        .byte	"NEWLINE    "
        .byte	"NOGAPNOBACTERIA    "
        .byte	"NOICE    "
        .byte	"OXYRON    "
        .byte	"OXYGENE    "
        .byte	"PARADOX    "
        .byte	"PLUSH    "
        .byte	"POO BRAIN    "
        .byte	"SCARAB    "
        .byte	"SCOOPEX    "
        .byte	"STARZ    "
        .byte	"STILL    "
        .byte	"TEK    "
        .byte	"THE SOLUTION    "
        .byte	"TRIAD    "
        .byte	"TRSI    "
        .byte	"TSA    "
        .byte	"TSCC    "
        .byte	"VIRGILL    "
	.byte	"                    ",2,2,"AND TO EVERYONE WHO VISITED DEADLINE 2021  "

        .byte	"                 BITSHIFTERS GREETS: ", 1,8,2,4
        .byte	"    ATE-BIT    "
        .byte	"CRTC    "
        .byte	"HOOY PROGRAM    "
        .byte	"ICEBIRD    "
        .byte	"INVERSE PHASE    "
        .byte	"KUEMMEL    "
        .byte	"LOGICOMA    "
        .byte	"POLARITY    "
        .byte	"PROGEN    "
        .byte	"PROXIMA    "
        .byte	"QUANTUM    "
        .byte	"RC55    "
        .byte	"RIFT    "
        .byte	"SLIPSTREAM    "
        .byte	"TOBACH    "
        .byte	"TORMENT    "
        .byte	"YM ROCKERZ    "

	.byte    "                                    TEXT STARTS AGAIN."
	.byte    2,8,"         10       9       8       7       6       5       4       3       2       1        BOOM!!       ",1,4,"                          ",0
