; scrolltxt  
; change:  26.03.2023 Time: 13:37
;
;       End of txt   0
;       Pause   1,(0-255)
;       Speed   2,(1,2,4 max 8)
;       possible chars:
;        ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!,:()+-=;'
;       NO UMLAUTS 


    .byte 2,2  ; speed
    .byte 1,8,32 ; pause before start
    .byte 2,4,"CHIPO               ",1,10
    .byte 2,8,"                       DJANGO TWO          ",1,10
    .byte 2,2,"   WE ARE HAPPY TO PRESENT THIS NEW CHIPTUNE PACK "
    .byte "AT THE REVISION 2023   IN SAARBRUECKEN,   "
    .byte "AFTER 3 YEARS OF CORONA SHIT.              "
    .byte "THERE IS AGAIN FOR AMIGA, ARCHIMEDES AND ATARI STE.   "
;
    .byte "          CREDITS:               GFX:   TITUS              "
    .byte "CODE:   KIERAN + PHOENIX:QUANTUM (ARCHIMEDES)    "
    .byte "INSANE (ATARI STE)    "
    .byte "BODO (AMIGA)              "
    .byte "ADDITIONAL SHIT:   BIFAT              "
    .byte "MUSIC:   "
    .byte "SLIME,  "
    .byte "TRIACE,  "
    .byte "NE7,  "
    .byte "OKEANOS,  "
    .byte "DALEZY,  "
    .byte "SLASH,  "
    .byte "VIRGILL,  "
    .byte "CURT COOL,  "
    .byte "PUNNIK,  "
    .byte "4MAT,  "
    .byte "LORD,  "
    .byte "MAZE,  "
    .byte "AND TOBACH  "
;
    .byte  "                               "
    .byte "HERE IS BODO AT THE KEYS:        "
    .byte "I HOPE YOU LIKE YOUR NEW CHIPTUNE PACK. "
    .byte "I HAVE HAD A LOT OF FUN TO DEVELOP IT AND  "
    .byte "I AM HAPPY TO PRESENT YOU THE GREAT SONGS! "
    .byte "THE SONG FROM SLIME IS FROM FEBRUARY 1995, "
    .byte "BUT I THINK IT WAS NEVER RELEASED BEFORE. "              
    .byte "I FOUND IT ON MY OLD HARDDISK :)              "
    .byte "I HAVE CORONA AS I WRITE THIS, "
    .byte "BUT IT IS ALMOST GONE AND IT WAS NOT VERY BAD.  "            
    .byte "BETTER NOW THAN AT THE REVISION PARTY.                   "
    .byte "REGARDING CHIPO DANJGO1, NOSFERATU SAID THAT THE SCROLL "
    .byte "TEXT IS TOO SHORT, SO I WRITE MORE THIS TIME. "
    .byte "YOU CAN THANK HIM FOR THAT ;)   "
    .byte "BUT I DO NOT THINK, I CAN WRITE AS MUCH AS THE "
    .byte "GROUP THRUST DID AT THE TIME.            "
    .byte "I DO NOT KNOW WHEN I WILL GET SOMETHING "
    .byte "FOR THE AMIGA CODE AGAIN, "
    .byte "BECAUSE I FEEL THAT MY PET IS CALLING. "
    .byte "BUT DO NOT WORRY THERE WILL BE MORE CHIPO DJANGOS. "
    .byte "                                "
    .byte "AND DO NOT FORGET:     "
    .byte "NEVER GIVE UP -    ",1,2
    .byte "STAY AMIGA!        ",1,5
    .byte "           NO ATARI - NO FUN! ",1,5
    .byte "           ONLY ARCHIMEDES ",1,2
    .byte "MAKES IT POSSIBLE!  ",1,5
    .byte "         ...END OF BODO "
    .byte "                       "
;
   .byte "CURT COOL IS WRITING. I AM HAPPY TO "
   .byte "BE PART OF THE CHIPO DJANGO FAMILY "
   .byte "ONCE AGAIN, AND HOPEFULLY THIS RATHER "
   .byte "QUICKLY MADE TUNE MAKES SENSE. "
   .byte "I HOPE TO SEE AND HEAR YOU "
   .byte "(YES, YOU, IN FRONT OF THE SCREEN!) "
   .byte "AT REVISION THIS YEAR (IT IS NOW 2023). "
   .byte "AND, REMEMBER TO SEND YOUR AMIGA AND C64 "
   .byte "DISKS AND DISK IMAGES FOR ARCHIVAL AT KESTRA, "
   .byte "AMP AND CSDB. WRITE ME AT CURTCOOL(AT)DEPTH.ORG "
   .byte "TO SUPPORT, OR JOIN #DISKRIPPING AT DEMOZOO DISCORD "
   .byte "- LET US KEEP THE OLD DATA ALIVE. "
   .byte "ALSO GREETS TO MY FRIENDS IN DEPTH "
   .byte "(30 YEARS THIS SUMMER!), FNUQUE, LOONIES, "
   .byte "FOCUS DESIGN, RABENAUGE (FOR MAKING THIS!), "
   .byte "NONAME, DUB, NAH-KOLOR, MOODS PLATEAU, OFFENCE, "
   .byte "ALCATRAZ, LEMON., NECTARINE, THE ELECTRONIC KNIGHTS, "
   .byte "MOONSHINE, GENESIS PROJECT, DESIRE, PACIFIC, NATURE,  "
   .byte "NUKLEUS, INSANE, UP ROUGH, REBELS, TRSI, SPACEBALLS, "
   .byte "RESISTANCE, PLANET JAZZ, BOOZOMBIES, BRAINSTORM, HAUJOBB, "
   .byte "EPHIDRENA, IRIS, TRAKTOR AND ALL I FORGOT (SORRY!)         "
   .byte "                       "
;
   .byte "     VIRGILL IS HERE:  "
   .byte "AMIGA MOD TRACKER MUSIC, "
   .byte "A GENRE QUITE UNIQUE,  "
   .byte "IT STARTED ON THE AMIGA, "
   .byte "WITH SOFTWARE TECHNIQUE. "
   .byte "USING SAMPLES AND SYNTHESIZERS, "
   .byte "TRACKERS MADE A SOUND, "
   .byte "COMPLEX RHYTHMS AND FAST TEMPOS, "
   .byte "TO MAKE THE SPEAKERS POUND. "
   .byte "IT MAY BE OLD, BUT STILL IT LIVES, "
   .byte "IN THE HEARTS OF MANY FANS, "
   .byte "AMIGA MOD TRACKER MUSIC, "
   .byte "FOREVER MAKING JAMS.       "
   .byte "                       "	
;
   .byte "YO! KIERAN AT THE KEYS NOW. BIG THANKS TO BODO FOR ASKING ME TO "
   .byte "COLLABORATE ON THIS MUSICDISK FROM THE BEGINNING FOR THE ARCHIE "
   .byte "VERSION.    IT HAS BEEN A LOT OF FUN TO MAKE AND AN HONOUR TO PRESENT "
   .byte "THIS FANTASTIC SELECTION OF TUNES FROM SUCH TALENTED MUSICIANS AT "
   .byte "REVISION 2023!    THIS IS MY FIRST TIME AT THE PARTY IN PERSON, "
   .byte "AFTER BEING THWARTED BY THE DREADED COVID IN 2020.     I LOOK FORWARD "
   .byte "TO MEETING MANY OF YOU THERE AND WHO KNOWS WHAT NEW COLLABORATIONS "
   .byte "MAY COME OUT OF IT...     THE ACORN ARCHIMEDES IS SUCH A CAPABLE "
   .byte "MACHINE, WE'VE ONLY JUST GOT STARTED!     GREETS TO MY FELLOW "
   .byte "BITSHIFTERS BACK HOME AND ACROSS THE ATLANTIC.    "
   .byte "     TIPSY HUGS     ", 1,5, "TO EVERYONE AT THE PARTY :)"
   .byte "                         "    
;
   .byte "HIER IST DALEZY: "
   .byte "WAR JA KLAR, DASS ES AUF DEM AMIGA KEINE EXTRA BUCHSTABEN GIBT! "
   .byte "ALSO MUSS ICH ES AUF DEUTSCH SCHREIBEN. "
   .byte "AM SONNTAGMORGEN UM 13 UHR 37 HABE ICH MIR EINEN CHEESEBURGER "
   .byte "AUS DEM KUEHLSCHRANK GEHOLT UND IHN KALT GEGESSEN. "
   .byte "BODO IST EIN NETTER JUNGE, MIT DEM MAN 1-14 BIER "
   .byte "HINTEREINANDER TRINKEN KANN. "
   .byte "DIESER CHIPTUNE IST IRGENDWANN ZWISCHEN BODO UND DEM "
   .byte "CHEESEBURGER ENTSTANDEN. "
   .byte "DIE GESCHICHTE ENDET HIER UND WIEDERHOLT SICH ENTSPRECHEND! "
   .byte "LBM.HERZCHENEMOJI "    
   .byte "                       "
;
    .byte "LORD OF SPREADPOINT ON THE KEYS FOR THIS MULTI "
    .byte "PLATFORM MUSICDISK: I CREATED A LONGPLAY VERSION "
    .byte "OFF MY VECTRAX VECTREX SONG FOR YOUR ENJOYMENT.   "
    .byte "THE HELP VOICESAMPLE IS SAMPLED FROM A VECTREX GAME: "
    .byte "IF YOU KNOW WHICH ONE, BE QUICK AND WRITE ME AN EMAIL AT "
    .byte "LORD AT SPREADPOINT.COM TO WIN A SPREADPOINT STICKER.         "
    .byte "GREETINGS TO ALL CHIPTUNE FANATICS AND THE DEMOSCENE "
    .byte "FREAKS.        "
    .byte "JOIN THE POWER!    ",1,5
    .byte "             ...END OF LORD          "
    .byte "                       "
;
    .byte "HI, 4MAT HERE.  I HAVEN'T WRITTEN A PROPER CHIP MOD FOR YEARS "
    .byte "SO THOUGHT I'D TRY SOMETHING A BIT DIFFERENT.  THIS ONE USES THE "
    .byte "INVERT LOOP COMMAND ACROSS PRETTY MUCH ALL THE SAMPLES, WHICH IS "
    .byte "WHY IT HAS TO PATTERN LOOP AT THE END. I NEVER USED THIS COMMAND "
    .byte "IN THE OLD DAYS BUT IT SEEMS A LOT MORE VERSATILE THAN I THOUGHT, "
    .byte "FOR EXAMPLE YOU CAN CREATE A SMOOTH PWM SQUARE WAVE BY SIMPLY "
    .byte "MAKING YOUR WHOLE WAVEFORM THE SAME VALUE. THIS WAS THE DREAM BACK "
    .byte "IN THE OLD DAYS OF CHIP MODULES AND IT WAS IN THE EDITOR ALL ALONG. "
    .byte ":)  THANKS TO THE MUSICDISK CODERS FOR IMPLEMENTING THIS COMMAND IN "
    .byte "THE DRIVER."
    .byte "                         "
;
    .byte "HELLO! TOBACH HERE, GLAD TO FINALLY BE DOING MUSIC ON A "
    .byte "MUSICDISK THAT ISN'T MY OWN! ALONG WITH SUCH BIG NAMES TOO... "
    .byte "LET'S HOPE THIS FIRST PROPER VENTURE INTO THE MOD FORMAT "
    .byte "ISN'T MY LAST! HOPE YOU ALL HAVE A GREAT REVISION 2023! "
    .byte "GREETZ TO TITAN, TUHB, POO-BRAIN AND ALL THE UK SCENE CREW."
    .byte "                         "	
;
   .byte"HELLO AND WELCOME TO SLASH SCROLLTEXT. "
   .byte"IT WAS A PLEASURE TO BE INVITED TO CHIPO DJANGO 1 "
   .byte"SO HERE IS MY CONTRIBUTION FOR ISSUE 2. "
   .byte"LETS MAKE THE CHIPMUSIC SCENE GROW TOGETHER - "
   .byte"GREETINGS TO THE AMIGASCENE / SLASH"
   .byte "                         "
;
    .byte "TITUS WRITING HERE. HEYA LADYS AND GENTS!"
    .byte "I HAVE NEVER BEEN A GREAT WRITER OF SCROLLTEXTS."
    .byte "ALL THIS SOCIAL PRESSURE FOR SOME LINES OF TEXT! ;). "
    .byte "SO I JUST SEND MY PERSONAL HUGS TO MY FRIENDS "
    .byte "IN THE SCENE AND WISH YOU SOME ENJOYABLE MOMENTS "
    .byte "WITH ALL THE GREAT SONGS IN CHIPO DJANGO 2. "
    .byte "I DO!. SO MY GREATEST THX TO ALL " 
    .byte "THESE TALENTED MUSICIANS WHO MADE THIS POSSIBLE."
    .byte "KUDOS TO YOU! TITUS - ATH0+ "
;         12345678901234567890
    .byte "                         "	
    .byte "GREETINGS FROM RABENAUGE AND BITSHIFTERS FLY OUT TO:",1,4
    .byte "   "
    .byte 2,8,"ABYSS    "
    .byte "ABYSS CONNECTION    "
    .byte "ALTAIR    "
    .byte "ATE-BIT    "
    .byte "ATLANTIS    "
    .byte "ATTENTION WHORE    "
    .byte "BAUKNECHT    "   
    .byte "CRTC    "
    .byte "CYANOACRYLATE DREAMS    "
    .byte "DANISH GOLD    "
    .byte "DELYSID    "
    .byte "DESIRE    "
    .byte "DEAD HACKERS SOCIETY    "
    .byte "DEADLINERS    "
    .byte "DIGITAL DEMOLITION KREW    "
    .byte "EXCESS    "
    .byte "FINNISH GOLD    "
    .byte "FTC    "
    .byte "GENESIS PROJECTS    "
    .byte "GNUMPF POSSE    "
    .byte "GHOSTOWN     "
    .byte "HAUJOBB    "
    .byte "HOOY PROGRAM    "
    .byte "HOTSTUFFERS    "
    .byte "HOLON    "
    .byte "ICEBIRD    "
    .byte "INSANE    "
    .byte "INVERSE PHASE    "
    .byte "JAC    "
    .byte "K2    "
    .byte "KUEMMEL    "
    .byte "LOGICOMA    "
    .byte "LOONIES    "
    .byte "MANIACS OF NOISE    "
    .byte "MAYDAY    "
    .byte "MELON    "
    .byte "MOODS PLATEAU    "
    .byte "MTP    "
    .byte "MYSTIC BYTES    "
    .byte "NEWLINE    "
    .byte "NOGAPNOBACTERIA    "
    .byte "NOICE    "
    .byte "OXYRON    "
    .byte "OXYGENE    "
    .byte "PARADOX    "
    .byte "PLUSH    "
    .byte "POO BRAIN    "
    .byte "PROGEN    "
    .byte "PROXIMA    "
    .byte "RIFT    "
    .byte "RBBS    "
    .byte "SCARAB    "
    .byte "SCOOPEX    "
    .byte "SLIPSTREAM    "
    .byte "SPREAPOINT    "
    .byte "STARZ    "
    .byte "STILL    "
    .byte "TEK    "
    .byte "THE SOLUTION    "
    .byte "TITAN    "
    .byte "TORMENT    "
    .byte "TRIAD    "
    .byte "TRSI    "
    .byte "TSA    "
    .byte "TSCC    "   
    .byte "YM ROCKERZ    "
    .byte "                    AND YOU!            ",1,5
    .byte 2,2
    .byte "                                                  "
    .byte "   OVER AND OUT                                                   "
    .byte 1,20  ; pause
    .byte 0   ; end of text
