; scrolltxt  
; change:  16.03.2023
;
;       End of txt   0
;       Pause   1,(0-255)
;       Speed   2,(1,2,4 max 8)


    ;   possible chars:
    ; ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!,:()+-=;'
    .byte 2,2  ; speed
    .byte 1,8,32 ; pause before start
    .byte 2,4,"CHIPO               ",1,10
    .byte 2,8,"                       DJANGO TWO          ",1,10
    .byte 2,2,"   WE ARE HAPPY TO PRESENT THIS NEW CHIPTUNE PACK "
    .byte "AT THE REVISION 2023   IN SAARBRUECKEN,   "
    .byte "AFTER 3 YEARS OF CORONA SHIT.              "
    .byte "THERE IS AGAIN FOR AMIGA, ARCHIMEDES AND ATARI STE.   "
;
    .byte "          CREDITS:               GFX:   TITUS              "
    .byte "CODE:   KIERAN + PHOENIX:QUANTUM (ARCHIMEDES)    "
    .byte "INSANE (ATARI STE)    "
    .byte "BODO (AMIGA)              "
    .byte "ADDITIONAL SHIT:   BIFAT              "
    .byte "MUSIC:   "
    .byte "SLIME,  "
    .byte "TRIACE,  "
    .byte "NE7,  "
    .byte "OKEANOS,  "
    .byte "DALEZY,  "
    .byte "SLASH,  "
    .byte "VIRGILL,  "
    .byte "CURT COOL,  "
    .byte "PUNNIK,  "
    .byte "4MAT,  "
    .byte "LORD,  "
    .byte "MAZE  "
;
    .byte  "                               "
    .byte "HERE IS BODO AT THE KEYS:        "
    .byte "I HOPE YOU LIKE YOUR NEW CHIPTUNE PACK. "
    .byte "I HAVE HAD A LOT OF FUN TO DEVELOP IT AND  "
    .byte "I AM HAPPY TO PRESENT YOU THE GREAT SONGS! "
    .byte "THE SONG FROM SLIME IS FROM FEBRUARY 1995, "
    .byte "BUT I THINK IT WAS NEVER RELEASED BEFORE. "              
    .byte "I FOUND IT ON MY OLD HARDDISK :)              "
    .byte "I HAVE CORONA AS I WRITE THIS, "
    .byte "BUT IT IS ALMOST GONE AND IT WAS NOT VERY BAD.  "            
    .byte "BETTER NOW THAN AT THE REVISION PARTY.                   "
    .byte "REGARDING CHIPO DANJGO1, NOSFERATU SAID THAT THE SCROLL "
    .byte "TEXT IS TOO SHORT, SO I WRITE MORE THIS TIME. "
    .byte "YOU CAN THANK HIM FOR THAT ;)   "
    .byte "BUT I DO NOT THINK, I CAN WRITE AS MUCH AS THE "
    .byte "GROUP THRUST DID AT THE TIME.            "
    .byte "I DO NOT KNOW WHEN I WILL GET SOMETHING "
    .byte "FOR THE AMIGA CODE AGAIN, "
    .byte "BECAUSE I FEEL THAT MY PET IS CALLING. "
    .byte "BUT DO NOT WORRY THERE WILL BE MORE CHIPO DJANGOS. "
    .byte "                                   "
    .byte "AND DO NOT FORGET:     "
    .byte "NEVER GIVE UP -    ",1,2
    .byte "STAY AMIGA!        ",1,5
    .byte "           NO ATARI - NO FUN! ",1,5
    .byte "           ONLY ARCHIMEDES ",1,2
    .byte "MAKES IT POSSIBLE!  ",1,5
    .byte "         ...END OF BODO "
    .byte "                       "
;    
    .byte "LORD OF SPREADPOINT ON THE KEYS FOR THIS MULTI "
    .byte "PLATFORM MUSICDISK: I CREATED A LONGPLAY VERSION "
    .byte "OFF MY VECTRAX VECTREX SONG FOR YOUR ENJOYMENT.   "
    .byte "THE HELP VOICESAMPLE IS SAMPLED FROM A VECTREX GAME: "
    .byte "IF YOU KNOW WHICH ONE, BE QUICK AND WRITE ME AN EMAIL AT "
    .byte "LORD AT SPREADPOINT.COM TO WIN A SPREADPOINT STICKER.         "
    .byte "GREETINGS TO ALL CHIPTUNE FANATICS AND THE DEMOSCENE "
    .byte "FREAKS.        "
    .byte "JOIN THE POWER!    ",1,5
    .byte "             ...END OF LORD          "
    .byte "                       "
; 
   .byte "TITUS WRITING HERE. HEYA LADYS AND GENTS!"
    .byte "I HAVE NEVER BEEN A GREAT WRITER OF SCROLLTEXTS."
    .byte "ALL THIS SOCIAL PRESSURE FOR SOME LINES OF TEXT! ;). "
    .byte "SO I JUST SEND MY PERSONAL HUGS TO MY FRIENDS "
    .byte "IN THE SCENE AND WISH YOU SOME ENJOYABLE MOMENTS "
    .byte "WITH ALL THE GREAT SONGS IN CHIPO DJANGO 2. "
    .byte "I DO!. SO MY GREATEST THX TO ALL " 
    .byte "THESE TALENTED MUSICIANS WHO MADE THIS POSSIBLE."
    .byte "KUDOS TO YOU! TITUS - ATH0+ "
;         12345678901234567890
    .byte "                         "	
    .byte "OUR GREETINGS GO TO:",1,4
    .byte "   "
    .byte 2,8,"ABYSS    "
    .byte "ABYSS CONNECTION    "
    .byte "ALTAIR    "
    .byte "ATE-BIT    "
    .byte "ATLANTIS    "
    .byte "ATTENTION WHORE    "
    .byte "BAUKNECHT    "   
    .byte "CRTC    "
    .byte "CYANOACRYLATE DREAMS    "
    .byte "DANISH GOLD    "
    .byte "DELYSID    "
    .byte "DESIRE    "
    .byte "DEAD HACKERS SOCIETY    "
    .byte "DEADLINERS    "
    .byte "DIGITAL DEMOLITION KREW    "
    .byte "EXCESS    "
    .byte "FINNISH GOLD    "
    .byte "FTC    "
    .byte "GENESIS PROJECTS    "
    .byte "GNUMPF POSSE    "
    .byte "GHOSTOWN     "
    .byte "HAUJOBB    "
    .byte "HOOY PROGRAM    "
    .byte "HOTSTUFFERS    "
    .byte "HOLON    "
    .byte "ICEBIRD    "
    .byte "INSANE    "
    .byte "INVERSE PHASE    "
    .byte "JAC    "
    .byte "K2    "
    .byte "KUEMMEL    "
    .byte "LOGICOMA    "
    .byte "LOONIES    "
    .byte "MANIACS OF NOISE    "
    .byte "MAYDAY    "
    .byte "MELON    "
    .byte "MOODS PLATEAU    "
    .byte "MTP    "
    .byte "MYSTIC BYTES    "
    .byte "NEWLINE    "
    .byte "NOGAPNOBACTERIA    "
    .byte "NOICE    "
    .byte "OXYRON    "
    .byte "OXYGENE    "
    .byte "PARADOX    "
    .byte "PLUSH    "
    .byte "POO BRAIN    "
    .byte "PROGEN    "
    .byte "PROXIMA    "
    .byte "RIFT    "
    .byte "RBBS    "
    .byte "SCARAB    "
    .byte "SCOOPEX    "
    .byte "SLIPSTREAM    "
    .byte "SPREAPOINT    "
    .byte "STARZ    "
    .byte "STILL    "
    .byte "TEK    "
    .byte "THE SOLUTION    "
    .byte "TITAN    "
    .byte "TORMENT    "
    .byte "TRIAD    "
    .byte "TRSI    "
    .byte "TSA    "
    .byte "TSCC    "   
    .byte "YM ROCKERZ    "
    .byte "                    AND YOU!            ",1,5
    .byte 2,2
    .byte "                                                  "
    .byte "   OVER AND OUT                                                   "
    .byte 1,10  ; pause
    .byte 0   ; end of text
